export { default as Image } from './image/Image.tsx'
export { default as Text } from './text/Text.tsx'
export { default as Title } from './title/Title.tsx'
export { default as Modal } from './modal/Modal.tsx'
export { default as Drawer } from './drawer/Drawer.tsx'
export { default as Tabs } from './tabs/Tabs.tsx'
export { default as Box } from './box/Box.tsx'
